### PR TITLE
Update interceptor-service.ts

### PR DESCRIPTION
**Pull request by pafailly**
You forgot to pass the body object in the POST request

### CODE REVIEW

**Comment by pafailly** [comment]
Or you should modify your function declaraction of **post** and remove the _body_ from it, so it can be passed via the _options_ object in order to be forwarded to the **@angular2/http** code

**Comment by voliva** [comment]
Right, my mistake. I will also update all other methods in a minute.
And I'd like my implementation to be as compatible as possible with the original **@angular/http**. If I remove the body from these methods, it won't

**Comment by voliva** [comment]
Thank you very much for your contribution!

**Comment by pafailly** [comment]
My pleasure ;)

**Pull request merged**
